version: '3'

services:
  database:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=123456
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  yami_demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - database

volumes:
  oracle_data:
